//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maiswan.Passwhat.WpfApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Maiswan.Passwhat.WpfApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maiswan.Passwhat.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build {0}.
        /// </summary>
        public static string Build {
            get {
                return ResourceManager.GetString("Build", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied password {0} to clipboard.
        /// </summary>
        public static string CopiedPasswordLog {
            get {
                return ResourceManager.GetString("CopiedPasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied Passwords.
        /// </summary>
        public static string CopiedPasswords {
            get {
                return ResourceManager.GetString("CopiedPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string CustomSet {
            get {
                return ResourceManager.GetString("CustomSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digits.
        /// </summary>
        public static string Digit {
            get {
                return ResourceManager.GetString("Digit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are passwords in the copy list. Do you want to exit?.
        /// </summary>
        public static string ExitConfirmation {
            get {
                return ResourceManager.GetString("ExitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generated password {0}.
        /// </summary>
        public static string GeneratedPasswordLog {
            get {
                return ResourceManager.GetString("GeneratedPasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English letters.
        /// </summary>
        public static string Latin {
            get {
                return ResourceManager.GetString("Latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No copied passwords yet.
        /// </summary>
        public static string NoCopiedPasswords {
            get {
                return ResourceManager.GetString("NoCopiedPasswords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak password.
        /// </summary>
        public static string PasswordWeak {
            get {
                return ResourceManager.GetString("PasswordWeak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed password {0}.
        /// </summary>
        public static string RemovedPasswordLog {
            get {
                return ResourceManager.GetString("RemovedPasswordLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbols.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
    }
}
